# Generated by Django 5.0.3 on 2024-03-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='user_name',
            field=models.CharField(default='admin', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
