# Generated by Django 5.0.3 on 2024-03-17 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.vacancy'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
