# Generated by Django 5.0.3 on 2024-03-18 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.car'),
        ),
    ]
