# Generated by Django 5.0.3 on 2024-03-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_owner_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
